<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="83171" started-at="2018-11-01T10:14:36Z" finished-at="2018-11-01T10:15:59Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="83171" started-at="2018-11-01T10:14:36Z" finished-at="2018-11-01T10:15:59Z">
      <class name="com.autopilot.TestCases.InstancePageTest">
        <test-method status="PASS" signature="preTestcondition()[pri:0, instance:com.autopilot.TestCases.InstancePageTest@457e2f02]" name="preTestcondition" is-config="true" duration-ms="49603" started-at="2018-11-01T15:44:36Z" finished-at="2018-11-01T15:45:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preTestcondition -->
        <test-method status="FAIL" signature="submitFormTest()[pri:0, instance:com.autopilot.TestCases.InstancePageTest@457e2f02]" name="submitFormTest" duration-ms="33494" started-at="2018-11-01T15:45:25Z" finished-at="2018-11-01T15:45:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Data Saved Successfully] but found [Please all questions mandatory]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Data Saved Successfully] but found [Please all questions mandatory]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.autopilot.TestCases.InstancePageTest.submitFormTest(InstancePageTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitFormTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.autopilot.TestCases.InstancePageTest@457e2f02]" name="tearDown" is-config="true" duration-ms="0" started-at="2018-11-01T15:45:59Z" finished-at="2018-11-01T15:45:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.autopilot.TestCases.InstancePageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
